RMerl/asuswrt-merlin.ng

release/src/router/others/entware-setup.sh
Multiple mounts of usb disk, after reboot, the mount directory changes, resulting in the entware directory not found.
=> Fix multiple mount usb disks, after restart, entware can not be started

release/src/router/www/js/table/table.js
There are a number of click handlers that are broken due to an undefined event variable.
The one that I noticed specifically prevents you from removing port trigger rules, which fails on line 1301.
I'm not exactly sure if/where the others are used, but they have the same issue code-wise, so I fixed them also.
=> Fix several broken click event handlers

release/src-rt-5.02hnd/hostTools/jffs2/mkfs.jffs2.c, release/src-rt-5.02hnd/hostTools/mtd-utils-20090606.patch, release/src-rt-5.02hnd/hostTools/squashfs_4.2/mksquashfs.c, release/src-rt-5.02hnd/hostTools/squashfs_4.2/unsquashfs.c, release/src/router/libevent-2.0.21/test/Makefile.am
On Ubuntu Disco (19.04), compilation fails with newer tools like automake and glibc.
Changes:
- **automake**: newer version dislike the use of "top_srcdir" in libevent's Makefile. https://github.com/libevent/libevent/commit/a55514eeed96b9bf9a16fbed1a709dfcce5a6080
- **glibc**: extra include <sys/sysmacros.h> needed for some macros.
Tested on Ubuntu Disco with automake 1.16.1 and glibc 2.29.
_Note: I realize patching a patch file is hack-y, but unfortunately this seems like the least intrusive way without touching the Makefiles._
=> Fix compilation on modern hosts

release/src/router/www/cloud_main.asp
works in Chrome 75 and Firefox 67
"rules" is [non-standard](https://drafts.csswg.org/cssom/#cssstylesheet) and does not work in Firefox 67
This results in an unhandled exception and failure to execute all of the script on the page
The visibile manifestation is that the aicloud Uninstall button remains visible because [this](https://github.com/RMerl/asuswrt-merlin.ng/blob/master/release/src/router/www/cloud_main.asp#L81) line never executes.
=> use a standard cssRules (instead of rules) property of CSSStyleSheet

release/src/router/rc/init.c
Mainline branch has duplicate dnspriv flags
=> rc: remove duplicate dnspriv from RC flags

release/src/router/rc/dnsfilter.c
DNSFilter is only writing IPv6 options 5 & 6 to dnsmasq.conf since the other choices have an index 13 or greater. This change allows the remaining options to be written.
=> rc: fix dnsfilter IPv6 additions to dnsmasq.conf

release/src/router/www/Advanced_ASUSDDNS_Content.asp
Field text appears black in the UI
=> webui: fix typo in DDNS page

release/src/router/others/vpnrouting.sh
Remove unnecessary echos
Standardize use of quotes for variables and echo statements to output files
Standardize use of ${instance} in code for readability
Remove unnecessary backslash escape character before '.' when setting file name vars at start
Tune code for VPN_IP_LIST to collect the six nvram parms. 
Replace code in back ticks with $()
Tune code checking if parm has values or no values with -n and -z operators
=> vpnrouting.sh code optimization

release/src/router/others/vpnrouting.sh
Ensure default route for ovpnc* table always gets set and that killswitch always adds prohibit rule.
As it is now, if you want to setup a VPN client using custom IPSET routing or similar, you have to either do it completely manually, or define a dummy client in the webui in order for the routing table to be built properly. Unless I'm missing something, there is no reason not to always create the client routing table. 
Aside from the base logic fix, I also changed the condition used for adding the client routing table default route, since I believe it was an actual bug. If it was indeed correct before, I will change that condition back. The line in question is 199/195 `if [ -n "$route_net_gateway" ]` -> `if [ -n "$route_vpn_gateway" ]`
Tested on an RT-AC68U by mounting my version over …
=> Make VPN policy routing mode work without requiring webui client rules

release/src/router/shared/network_utility.c
Fix the `convert_subnet_mask_to_cidr` from `network_utils.c` to work correctly when the LAN netmask contains values other than 255 or 0 on little endian systems.
There is a missing byte-order conversion before calling `bit_count`. This caused a value of -1 to be returned even for valid masks. As a result, the firewall rules generated for a VPN server would end up with an invalid rule like below which prevented the server from working:
`iptables -I OVPN -i tun22 ! -d 192.168.1.1/-1 -j ACCEPT`
Also made a slight adjustment to `bit_count` to correctly treat malformed masks such as `0.255.255.0` as invalid.
Tested using the attached test program compiled and run on an RT-AC68U running firmware 384.19. The output is as follows:
[cidr_fix.c](https://github.com/RMerl/asuswrt-merlin.ng/files/54403 …
=> Fix vpn server access in LAN-only and WAN-only modes

release/src/router/www/QoS_Stats.asp
As soon as a connection is excluded by the first populated filter, stop checking additional filters and proceed to the next connection in the loop.
=> webui: stop processing more filters once connection is excluded

release/src/router/rc/qos.c
Upload classes 1:10 through 1:40 are missing on the upload WAN interface. This commit reverts to the code block from 386.1beta4.
=> rc: fix bad merge in qos.c from GPL_41700

release/src/router/iproute2-4.3/iproute2-4.3.0/tc/q_cake.c
Address negative deficit values overflowing on stats output.
```
class cake 8005:42b parent 8005:
(dropped 44, overlimits 0 requeues 0)
backlog 10598b 7p requeues 0
deficit 4294967060 count 16 dropping drop_next -4295.0s blue_prob 0
```
=> iproute2-4.3: fix display of negative deficit and drop_next values

release/src/router/www/UUAccelerator.asp, release/src/router/www/sysdep/FUNCTION/ROG_UI/GameBoost.asp, release/src/router/www/sysdep/FUNCTION/ROG_UI/GameDashboard.asp
When the type is "asuswrt", the Accelerator web UI show "The router fails to connect to the network" and can't work as expected
Modify the URL to "type=asuswrt-merlin", it work normally again
tested on AC88u AX88u AC86u AX86u AC1900P
refer:
router type define
install.sh from https://router.uu.163.com/api/script/install?type=asuswrt-merlin
uuplugin_monitor.sh from https://router.uu.163.com/api/script/monitor?type=asuswrt-merlin
fourm solution discussion
https://koolshare.cn/forum.php?mod=redirect&goto=findpost&ptid=179485&pid=2417559
https://koolshare.cn/forum.php?mod=viewthread&tid=179485
https://koolshare.cn/forum.php?mod=redirect&goto=findpost&ptid=192048&pid=2515316
=> Fix NetEase UU Game Accelerator model type

release/src/router/rc/qos.c
This would allow user customizations in DLOPTIONS and ULOPTIONS to override the firmware-generated OVERHEAD and FRAMING via Cake keywords (docsis, pppoe-ptm) in DLOPTIONS and ULOPTIONS.
=> rc: Rearrange Cake variable positions

release/src/router/www/Advanced_System_Content.asp, release/src/router/www/state.js
Ignore timezone text in parentheses which may include a dash in non-English languages and confuse the index logic.
Fixes RMerl#726
=> webui: Fix timezone detection

release/src/router/rom/rom/etc/profile, release/src/router/rom/rom/etc/profile.hnd
/jffs/configs/profile.add is sourced by /etc/profile regardless of the state of “Enable JFFS custom scripts and configs“. This PR will only source the profile if JFFS custom scripts and configs is enabled. This would be in alignment with the rest of the custom config files’ behavior.
=> rom: Only source profile.add when custom configs enabled

release/src/router/openvpn/doc/man-sections/cipher-negotiation.rst
Missing cipher-negotiation.rst causes build failure when docs try to
build.  Add file from openvpn 2.5.5 release.
Signed-off-by: Kumar Gala <galak@kernel.org>
=> openvpn: add missing cipher-negotiation.rst

release/src/router/httpd/sysinfo.c
Ensure output performs multiplications in float or uint64. Problem only likely to hit with large swap files at the moment.
Fixes problem reported at
https://www.snbforums.com/threads/displayed-memory-usage-error-in-webui.76204/page-2#post-734474
=> Avoid 32-bit overflow in GUI stats

release/src/router/httpd/data_arrays.c, release/src/router/rc/qos.c, release/src/router/rc/qos_multiwan.c, release/src/router/www/QoS_Stats.asp
* Fix transfer limits - undefined behaviour was stopping minimums from working
* Allow default rule to work when a transfer limit rule no longer applies
* Basic IPv6 support
* Fix imq0 download classification - mark restoration and masking
* Correct overheads
* Implement PTM
* Restore GUI display for download classification
Fuller detail in individual commit messages.
=> Assorted TQoS fixes

release/src/router/rc/qos.c
All wired download traffic is tagged as vlan1 and was seen on eth0, resulting in wired download traffic being limited to the upload bandwidth setting.
Restore previous behavior of all VLAN-tagged traffic on eth0 to be directed to 1:60 where the bandwidth limit is 1Gbps.
Fixes: 0bc048f77bf7c3f92291d2fba61a1a9e8a323a85 ("rc: tQoS fixes from upstream")
=> rc: fix tQoS wired download traffic limited by upload bandwidth

release/src/router/www/sysdep/FUNCTION/ROG_UI/tmcal.js, release/src/router/www/sysdep/GT-AC5300/www/tmcal.js, release/src/router/www/tmcal.js
Keep units consistent by respecting user dropdown choice. Previous behavior reduced KBs to MB, GB or TB in order to keep the displayed sum less than 10000. Also use comma separators to keep larger numbers more readable.
=> webui: Display Last 24 Hours Totals in KB when requested

release/src/router/rc/udhcpc.c
Add a second parameter to dhcpc-event user script calls to differentiate IPv4 DHCP events from IPv6 DHCPv6 or RA events. This maintains backward compatibility since existing scripts will ignore the optional second parameter (4 or 6).
=> rc: add dhcpc-event parameter for IPv4 vs IPv6 events

release/src/router/rc/common.c
1. line 1393: A typo `UCT` to `UTC`
2. line 1394: Write correct `tmpstr` which should be `JST-9` to /etc/TZ
See discussion [Chaotic UTC and local time in merlin](https://www.snbforums.com/threads/chaotic-utc-and-local-time-in-merlin.79268/post-767654) on the SNBForums.
Manually revise `/etc/TZ` from `JST` to `JST-9`.
```
JST-9
```
Now test the function of `date`.
```
Sat Jun 11 11:19:00 JST 2022
Sat Jun 11 02:19:27 UTC 2022
```
Perfect!
Signed-off-by: Shengjiang Quan <qsj287068067@126.com>
=> fix `JST` time zone error

README.md
The issue tracker isn't even enabled on this repo, so remove mention of it from the project readme.
=> Remove mention of GitHub issue tracker

release/src/router/www/Advanced_VPN_OpenVPN.asp
vpn_openvpn_desc2 already finish with Advanced Settings
Before 
After
=> Advanced Settings was showing twice

release/src/router/www/Tools_OtherSettings.asp
rstats_stime nvram is only 2 bytes since 382.x and cannot fit the value 168 for the “Every 1 week” dropdown selection.
Ref: https://github.com/RMerl/asuswrt-merlin.ng/commit/83b37275c1ddbf7b5e4e245fd1621201397a89f9
=> webui: remove rstats week option

release/src/router/others/cru
There are reported cases of cron jobs being lost under heavy cru activity (concurrent executions). Protect against concurrent add or deletes with a more robust locking mechanism using flock.
File descriptor 278 is used as it represents the letters C-R-U on a telephone keypad.
=> others: improve cru locking to prevent concurrent updates

release/src/router/rc/watchdog.c
Fix bracket typo preventing proper version display in log message.
Last update notification (before):
```
Feb 27 02:26:29 watchdog: New firmware version .._ is available.
```
Fixes 3c6300e818
=> rc: fix version parsing in watchdog

release/src/router/www/Advanced_Wireless_Survey.asp, release/src/router/www/client_function.js, release/src/router/www/js/table/table.js, release/src/router/www/sysdep/FUNCTION/SITE_SURVEY/Advanced_Wireless_Survey.asp
The table sorter is flawed.
When clicking a header it flips the sorting direction every time. Regardless if the header is already selected or not.
Expected behaviour:
- Default sorting direction is increasing on the first column. (Except for Site Survey where signal strength is sorted by descending order by default).
- Clicking a column header that is already selected: flip the direction.
- Clicking a column header which is **not** selected: the sorting direction defaults to increasing.
=> Fixed sorting when clicking on table header.

release/src/router/httpd/data_arrays.c
When trying to access **System Log - Active Connections** (`Main_ConnStatus_Content.asp`), when there are many (10000+) entries, the operation takes a long time (40-45s on my RT-AX88U) and nothing is displayed. This is due to `netstat-nat` sorting (`-r state`).
If letting the client handle the sorting in the datatable instead, the execution time can be reduced by at least 40%.
=> Removed sorting with netstat-nat, which added 40-45% execution time with many entries.

release/src/router/httpd/http.c
Two signedness checks are added to `wget()` function in `httpd/http.c`.
Without the checks, a wget request from the implementation to a malicious server with a crafted `Content-Length` parameter (or a valid `Content-Length` plus a crafted `Transfer-Encoding: chunked`) may lead to a consequent buffer over-read in the statement `len = fread(buf, 1, len, fp);`.
=> httpd: add two signedness check in httpd/http.c

release/src/router/openssl-1.1/crypto/bn/bn_gf2m.c, release/src/router/openssl-1.1/test/ec_internal_test.c
The following OpenSSL-1.1.1w patch has been ported from Debian Repository https://packages.debian.org/bullseye/openssl
CVE-2024-9143  Low-level invalid GF(2^m) parameters lead to OOB memory access.
=> Ported CVE-2024-9143 Low-level invalid GF(2^m) parameters lead to OOB memory access OpenSSL-1.1.1w fix from Debian Repo.

release/src/router/config/Makefile
gcc-15 complains that main() returns an int.
Without this, gcc errors out early in the build process.  I'm using Fedora 41 to run the builds.
=> Fix gcc-15 build

release/src/router/openssl-1.1/crypto/bn/bn_exp.c, release/src/router/openssl-1.1/crypto/ec/ec_lib.c, release/src/router/openssl-1.1/include/crypto/bn.h
The following OpenSSL-1.1.1w patch has been ported from Ubuntu Repository https://packages.ubuntu.com/focal/openssl
CVE-2024-13176 Fix timing side-channel in ECDSA signature computation.
Rework of #867
=> Ported CVE-2024-13176 fix for OpenSSL 1.1.1w from Ubuntu Repository.

release/src/router/www/state.js
state.js does not account for the presence of the DNS Director tab in this hard-coded tab count, leading to the "Switch Control" tab being highlighted when a user clicks the Profile sub-tab in the VLAN page.
=> webui: set correct tab when switching to VLAN Profile sub-tab

release/src/router/www/sysdep/FUNCTION/MULTISERVICE_WAN/Advanced_WAN_Content.asp
Prevents unique Merlin entries like Canadian Shield or Adguard from being overwritten by Asus’ remote json file.
=> webui: Ignore ASUS remote DoT json database on Multiservice WAN page

release/src/router/www/dot-servers.json
Correct copy/paste errors adding Control-D DoT servers from ASUS' online JSON DB.
Fixes: d011c506a28adc04d20fbe8c3f2254024bc12f73 ("webui: Add Control-D servers to DoT json database")
=> webui: fix Control-D DoT IPv4 addresses

release/src/router/rc/wan.c
The dns_local_cache nvram variable was removed in commit 33c0796. Cleanup this leftover check.
=> rc: disable obsolete dns_local_cache check
